# Changes here will be overwritten by Copier
_commit: v0.14.1
_src_path: gh:bhklab/bhklab-project-template
author_email: julianguyen.bhklab@gmail.com
author_full_name: Julia Nguyen
github_username: julianguyn
has_additional_authors: false
project_description: Investigation of synthetic lethal biomarkers
project_name: SL Biomarker
project_slug: sl-biomarker
publish_to_github: true
python_version: '3.12'
repo_location: julianguyn
